import type { SharedTheme } from '@themeforge/shared';

export const defaultDark: SharedTheme = {
  name: 'My Dark Theme',
  type: 'dark',
  colors: {
    'editor.background': '#1e1e1e',
    'editor.foreground': '#d4d4d4',
    'editor.lineHighlightBackground': '#2a2d2e',
    'editor.selectionBackground': '#264f78',
    'editor.selectionHighlightBackground': '#add6ff26',
    'editorWidget.background': '#252526',
    'editorWidget.border': '#454545',
    'sideBar.background': '#252526',
    'sideBar.foreground': '#cccccc',
    'sideBar.border': '#333333',
    'sideBarTitle.foreground': '#bbbbbb',
    'sideBarSectionHeader.background': '#00000000',
    'activityBar.background': '#333333',
    'activityBar.foreground': '#ffffff',
    'activityBar.inactiveForeground': '#ffffff66',
    'activityBar.border': '#333333',
    'activityBarBadge.background': '#007acc',
    'activityBarBadge.foreground': '#ffffff',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'statusBar.border': '#007acc',
    'titleBar.activeBackground': '#3c3c3c',
    'titleBar.activeForeground': '#cccccc',
    'titleBar.inactiveBackground': '#3c3c3c99',
    'titleBar.inactiveForeground': '#cccccc99',
    'terminal.background': '#1e1e1e',
    'terminal.foreground': '#cccccc',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiRed': '#cd3131',
    'terminal.ansiGreen': '#0dbc79',
    'terminal.ansiYellow': '#e5e510',
    'terminal.ansiBlue': '#2472c8',
    'terminal.ansiMagenta': '#bc3fbc',
    'terminal.ansiCyan': '#11a8cd',
    'terminal.ansiWhite': '#e5e5e5',
    'terminal.ansiBrightBlack': '#666666',
    'terminal.ansiBrightRed': '#f14c4c',
    'terminal.ansiBrightGreen': '#23d18b',
    'terminal.ansiBrightYellow': '#f5f543',
    'terminal.ansiBrightBlue': '#3b8eea',
    'terminal.ansiBrightMagenta': '#d670d6',
    'terminal.ansiBrightCyan': '#29b8db',
    'terminal.ansiBrightWhite': '#e5e5e5',
    'terminalCursor.foreground': '#d4d4d4',
    'breadcrumb.foreground': '#cccccc99',
    'breadcrumb.activeSelectionForeground': '#e8e8e8',
    'breadcrumb.focusForeground': '#e8e8e8',
    'tab.activeBorderTop': '#007acc',
    'panel.background': '#1e1e1e',
    'panel.border': '#80808059',
    'button.background': '#0e639c',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#1177bb',
    'input.background': '#3c3c3c',
    'input.border': '#00000000',
    'input.foreground': '#cccccc',
    'input.placeholderForeground': '#a6a6a6',
    'list.activeSelectionBackground': '#094771',
    'list.activeSelectionForeground': '#ffffff',
    'list.hoverBackground': '#2a2d2e',
    'list.inactiveSelectionBackground': '#37373d',
  },
  tokenColors: [
    {
      name: 'Comment',
      scope: 'comment',
      settings: { foreground: '#6a9955', fontStyle: 'italic' },
    },
    {
      name: 'Keyword',
      scope: 'keyword',
      settings: { foreground: '#569cd6' },
    },
    {
      name: 'Control Flow',
      scope: 'keyword.control',
      settings: { foreground: '#c586c0' },
    },
    {
      name: 'String',
      scope: 'string',
      settings: { foreground: '#ce9178' },
    },
    {
      name: 'Number',
      scope: 'constant.numeric',
      settings: { foreground: '#b5cea8' },
    },
    {
      name: 'Boolean / Null',
      scope: ['constant.language.boolean', 'constant.language.null'],
      settings: { foreground: '#569cd6' },
    },
    {
      name: 'Function Name',
      scope: 'entity.name.function',
      settings: { foreground: '#dcdcaa' },
    },
    {
      name: 'Function Call',
      scope: 'support.function',
      settings: { foreground: '#dcdcaa' },
    },
    {
      name: 'Variable',
      scope: 'variable',
      settings: { foreground: '#9cdcfe' },
    },
    {
      name: 'Parameter',
      scope: 'variable.parameter',
      settings: { foreground: '#9cdcfe' },
    },
    {
      name: 'Type Name',
      scope: ['entity.name.type', 'entity.name.class'],
      settings: { foreground: '#4ec9b0' },
    },
    {
      name: 'Type Annotation',
      scope: 'support.type',
      settings: { foreground: '#4ec9b0' },
    },
    {
      name: 'Operator',
      scope: 'keyword.operator',
      settings: { foreground: '#d4d4d4' },
    },
    {
      name: 'Punctuation',
      scope: 'punctuation',
      settings: { foreground: '#d4d4d4' },
    },
    {
      name: 'Import / Module',
      scope: ['keyword.control.import', 'entity.name.module'],
      settings: { foreground: '#c586c0' },
    },
    {
      name: 'Property',
      scope: 'entity.name.tag',
      settings: { foreground: '#4ec9b0' },
    },
  ],
};

export const defaultLight: SharedTheme = {
  name: 'My Light Theme',
  type: 'light',
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#000000',
    'editor.lineHighlightBackground': '#f0f0f0',
    'editor.selectionBackground': '#add6ff',
    'editor.selectionHighlightBackground': '#add6ff80',
    'editorWidget.background': '#f3f3f3',
    'editorWidget.border': '#c8c8c8',
    'sideBar.background': '#f3f3f3',
    'sideBar.foreground': '#424242',
    'sideBar.border': '#e7e7e7',
    'sideBarTitle.foreground': '#6f6f6f',
    'sideBarSectionHeader.background': '#00000000',
    'activityBar.background': '#2c2c2c',
    'activityBar.foreground': '#ffffff',
    'activityBar.inactiveForeground': '#ffffff66',
    'activityBar.border': '#2c2c2c',
    'activityBarBadge.background': '#007acc',
    'activityBarBadge.foreground': '#ffffff',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'statusBar.border': '#007acc',
    'titleBar.activeBackground': '#dddddd',
    'titleBar.activeForeground': '#333333',
    'titleBar.inactiveBackground': '#eeeeee',
    'titleBar.inactiveForeground': '#33333399',
    'terminal.background': '#ffffff',
    'terminal.foreground': '#333333',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiRed': '#cd3131',
    'terminal.ansiGreen': '#008000',
    'terminal.ansiYellow': '#795e26',
    'terminal.ansiBlue': '#0451a5',
    'terminal.ansiMagenta': '#bc05bc',
    'terminal.ansiCyan': '#0598bc',
    'terminal.ansiWhite': '#555555',
    'terminal.ansiBrightBlack': '#666666',
    'terminal.ansiBrightRed': '#cd3131',
    'terminal.ansiBrightGreen': '#14ce14',
    'terminal.ansiBrightYellow': '#b5ba00',
    'terminal.ansiBrightBlue': '#0451a5',
    'terminal.ansiBrightMagenta': '#bc05bc',
    'terminal.ansiBrightCyan': '#0598bc',
    'terminal.ansiBrightWhite': '#a5a5a5',
    'terminalCursor.foreground': '#000000',
    'breadcrumb.foreground': '#42424299',
    'breadcrumb.activeSelectionForeground': '#333333',
    'breadcrumb.focusForeground': '#333333',
    'tab.activeBorderTop': '#007acc',
    'panel.background': '#ffffff',
    'panel.border': '#e7e7e7',
    'button.background': '#007acc',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#006bb3',
    'input.background': '#ffffff',
    'input.border': '#cecece',
    'input.foreground': '#616161',
    'input.placeholderForeground': '#767676',
    'list.activeSelectionBackground': '#0060c0',
    'list.activeSelectionForeground': '#ffffff',
    'list.hoverBackground': '#e8e8e8',
    'list.inactiveSelectionBackground': '#e4e6f1',
  },
  tokenColors: [
    {
      name: 'Comment',
      scope: 'comment',
      settings: { foreground: '#008000', fontStyle: 'italic' },
    },
    {
      name: 'Keyword',
      scope: 'keyword',
      settings: { foreground: '#0000ff' },
    },
    {
      name: 'Control Flow',
      scope: 'keyword.control',
      settings: { foreground: '#af00db' },
    },
    {
      name: 'String',
      scope: 'string',
      settings: { foreground: '#a31515' },
    },
    {
      name: 'Number',
      scope: 'constant.numeric',
      settings: { foreground: '#098658' },
    },
    {
      name: 'Boolean / Null',
      scope: ['constant.language.boolean', 'constant.language.null'],
      settings: { foreground: '#0000ff' },
    },
    {
      name: 'Function Name',
      scope: 'entity.name.function',
      settings: { foreground: '#795e26' },
    },
    {
      name: 'Function Call',
      scope: 'support.function',
      settings: { foreground: '#795e26' },
    },
    {
      name: 'Variable',
      scope: 'variable',
      settings: { foreground: '#001080' },
    },
    {
      name: 'Parameter',
      scope: 'variable.parameter',
      settings: { foreground: '#001080' },
    },
    {
      name: 'Type Name',
      scope: ['entity.name.type', 'entity.name.class'],
      settings: { foreground: '#267f99' },
    },
    {
      name: 'Type Annotation',
      scope: 'support.type',
      settings: { foreground: '#267f99' },
    },
    {
      name: 'Operator',
      scope: 'keyword.operator',
      settings: { foreground: '#000000' },
    },
    {
      name: 'Import / Module',
      scope: ['keyword.control.import', 'entity.name.module'],
      settings: { foreground: '#af00db' },
    },
  ],
};
